<a href="https://colab.research.google.com/github/ntp3105/IISc-CCE-ML-AI-MLOps/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical AI and MLOps : Assignment 1

## Import libraries and fetch data

In [111]:
## DO NOT EDIT
import numpy as np
import pickle

!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-4LzDDmpH-v9mIgwDqa6cSF5XrVm-SXg' -O linear_regression.pkl
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-AtCVwrcpgFCvAD3gwkUz812DIxqK338' -O logistic_regression.pkl

X1_train, X1_test, Y1_train, Y1_test, X2_train, X2_test, Y2_train, Y2_test = [[] for _ in range(8)]

with open("/content/linear_regression.pkl", 'rb') as f:
    X1_train, X1_test, Y1_train, Y1_test = pickle.load(f)

with open("/content/logistic_regression.pkl", 'rb') as f:
    X2_train, X2_test, Y2_train, Y2_test = pickle.load(f)

--2023-08-31 21:11:34--  https://docs.google.com/uc?export=download&id=1-4LzDDmpH-v9mIgwDqa6cSF5XrVm-SXg
Resolving docs.google.com (docs.google.com)... 209.85.234.102, 209.85.234.101, 209.85.234.139, ...
Connecting to docs.google.com (docs.google.com)|209.85.234.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-10-0s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/r03nli93ul8vt0jotvncafn98j6hink5/1693516275000/06549736550030827657/*/1-4LzDDmpH-v9mIgwDqa6cSF5XrVm-SXg?e=download&uuid=32650993-da16-4df4-bbcb-57780081bfe4 [following]
--2023-08-31 21:11:34--  https://doc-10-0s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/r03nli93ul8vt0jotvncafn98j6hink5/1693516275000/06549736550030827657/*/1-4LzDDmpH-v9mIgwDqa6cSF5XrVm-SXg?e=download&uuid=32650993-da16-4df4-bbcb-57780081bfe4
Resolving doc-10-0s-docs.googleusercontent.com (doc-10-0s-docs.googleusercontent.com)... 64.233.191.132, 2607:f8b0:

In [124]:
X1_train = np.resize(X1_train, (len(X1_train), 1))
X1_test =  np.resize(X1_test,  (len(X1_test), 1))
Y1_train = np.resize(Y1_train, (len(Y1_train), 1))
Y1_test =  np.resize(Y1_test,  (len(Y1_test), 1))
print(X1_train[0:5])
print(X1_test.shape)
print(Y1_train.shape)
print(Y1_test.shape)

[[-8.85376401]
 [-2.5895495 ]
 [ 8.08186325]
 [-4.97550386]
 [ 5.49334111]]
(30, 1)
(70, 1)
(30, 1)


In [51]:
Y2_train = np.resize(Y2_train, (len(Y2_train), 1))
Y2_test =  np.resize(Y2_test,  (len(Y2_test), 1))
print(X2_train.shape)
print(X2_test.shape)
print(Y2_train.shape)
print(Y2_test.shape)

(70, 20)
(30, 20)
(70, 1)
(30, 1)


In [53]:

print(X1_train[0:5])
print(X1_test[0:5])
print(Y1_train[0:5])
print(Y1_test[0:5])

[[-8.85376401]
 [-2.5895495 ]
 [ 8.08186325]
 [-4.97550386]
 [ 5.49334111]]
[[ 6.26850875]
 [-5.75615029]
 [-5.98513959]
 [-9.76278328]
 [-6.04948187]]
[[-624.50354913]
 [ -13.24869745]
 [ 601.2775069 ]
 [-103.3916406 ]
 [ 201.44157479]]
[[ 291.87875938]
 [-163.34294373]
 [-184.56229109]
 [-844.96063406]
 [-190.84148613]]


In [52]:
print(X2_train[0])
print(X2_test[0])
print(Y2_train[0:5])
print(Y2_test[0:5])

[-0.67857138  2.7670727   2.03131422  0.3322455  -1.2361682  -0.48420497
 -1.6533102   0.17205938 -1.14020401 -1.02420001 -1.41826043  0.26769137
  0.39235085  0.49597238 -2.04503375  0.75743566  2.50947819  0.53326592
  0.92774064 -1.3631717 ]
[ 1.59980278  0.34209474  1.39349879 -1.44936033 -0.94399061  0.00816769
 -0.87028399 -1.49635521  0.66575811  1.06385996 -1.73467213  0.05441906
 -0.05293944  0.82191122  0.04120958 -1.71024922  0.49349984  0.124863
 -0.22401342  0.47682353]
[[0]
 [1]
 [1]
 [0]
 [0]]
[[0]
 [0]
 [0]
 [0]
 [1]]


## Problem 1: Linear Regression (2 Marks)

Train a linear regression model for the above set of data. Use MSE(Mean Squared Error) as the loss function.

Print out the train accuracy and test accuracy.

**Data**: X1_train, X1_test, Y1_train, Y1_test

In [114]:
### Write your code here
## Solve the question using normal equation


## Define the hypothesis function for linear regression
#Answer: Hypothesis/Cost_function = (np.sum(Y1_train - (bias + weight_1*X1_train) ))/len(Y1_train)
#print(Y1_train[0:5])

#Calculating baseline of error (Mean square error) before applying linear regression, so that we
#can compare error after applying linear regression, and assess if it has reduced or increased.
y_mean = Y1_train.mean()
y_pred_baseline = [y_mean]*len(Y1_train)
#print(y_pred_baseline)
Pre_training_error = Y1_train - y_pred_baseline
baseline_mse = np.sum(Pre_training_error**2)/len(Y1_train)
print("Baseline error:", baseline_mse)

## Use linear regression to train the model

Regression_coefficient = (np.dot(X1_train.T,X1_train)**-1)*np.dot(X1_train.T,Y1_train)
print("Regression_coefficient: ", Regression_coefficient)

## Compute the training and testing loss using MSE error
Post_training_error = np.sum((Y1_train - Regression_coefficient*X1_train)**2)/len(Y1_train)
print("Post Training Error: ", Post_training_error)

test_error = np.sum((Y1_test - Regression_coefficient*X1_test)**2)/len(Y1_test)
## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = Post_training_error
loss_test = test_error

print("Linear Regression")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)

Baseline error: 12859191.718880545
Regression_coefficient:  [[66.1311054]]
Post Training Error:  27415.39655697824
Linear Regression
Training Loss:  27415.39655697824
Testing  Loss:  44432.264978342


In [131]:
ones_column = np.ones((X1_train.shape[0], 1))
X1_train_mod = np.hstack((ones_column, X1_train))

ones_column = np.ones((X1_test.shape[0], 1))
X1_test_mod = np.hstack((ones_column, X1_test))

Y1_train_mod = np.resize(Y1_train, (len(Y1_train), 1))
Y1_test_mod =  np.resize(Y1_test,  (len(Y1_test), 1))

[[ 1.          6.26850875]
 [ 1.         -5.75615029]
 [ 1.         -5.98513959]
 [ 1.         -9.76278328]
 [ 1.         -6.04948187]]
[[ 6.26850875]
 [-5.75615029]
 [-5.98513959]
 [-9.76278328]
 [-6.04948187]]


In [133]:
### Write your code here
## Solve the question using normal equation


## Define the hypothesis function for linear regression
#Answer: Hypothesis/Cost_function = (np.sum(Y1_train - (bias + weight_1*X1_train) ))/len(Y1_train)
## Use linear regression to train the model

Regression_coefficients = np.dot(np.linalg.pinv(np.dot(X1_train_mod.T, X1_train_mod)), np.dot(X1_train_mod.T, Y1_train_mod))
print("Regression_coefficient: ", Regression_coefficients)

## Compute the training and testing loss using MSE error
Post_training_error = np.sum((Y1_train_mod - np.dot(X1_train_mod, Regression_coefficients))**2)/len(Y1_train_mod)
print("Post Training Error: ", Post_training_error)
test_error = np.sum((Y1_test_mod - np.dot(X1_test_mod, Regression_coefficients))**2)/len(Y1_test_mod)

## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = Post_training_error
loss_test = test_error
print("Linear Regression")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)


Regression_coefficient:  [[47.21637965]
 [65.15344921]]
Post Training Error:  25222.28423671403
Linear Regression
Training Loss:  25222.28423671403
Testing  Loss:  41716.624929654376


In [122]:
print("A:",np.dot(X1_train_mod, Regression_coefficients)[0:5])
print("trainY:", Y1_train_mod[0:5])
#print(np.sum((Y1_train_mod - np.dot(X1_train_mod, Regression_coefficient))**2)/len(Y1_train_mod))

A: [[127.77915978]
 [ 81.67003602]
 [ 88.71757466]
 [ 98.27660665]
 [ 89.76125962]]
trainY: [[-624.50354913]
 [ -13.24869745]
 [ 601.2775069 ]
 [-103.3916406 ]
 [ 201.44157479]]


## Problem 2: Polynomial Regression (2 Marks)

Solve the above problem using atleast 3 different hypothesis functions with polynomial degree 2, 3 and 4.

Print out the train accuracy and test accuracy. Write your inference on the results.

**Data**: X1_train, X1_test, Y1_train, Y1_test

### Polynomial Degree 2

In [ ]:
### Write your code here
## Define the hypothesis function



## Use polynomial regression to train the model



## Compute the training and testing loss



## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = 0
loss_test = 0

print("Polynomial Degree 2")
print("Training loss: ", loss_train)
print("Testing  loss: ", loss_test)

Polynomial Degree 2
Training Accuracy:  0
Testing  Accuracy:  0


### Polynomial Degree 3

In [ ]:
### Write your code here
## Define the hypothesis function



## Use polynomial regression to train the model



## Compute the training and testing loss



## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = 0
loss_test = 0

print("Polynomial Degree 3")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)

Polynomial Degree 3
Training Accuracy:  0
Testing  Accuracy:  0


### Polynomial Degree 4

In [ ]:
### Write your code here
## Define the hypothesis function



## Use polynomial regression to train the model



## Compute the training and testing loss



## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = 0
loss_test = 0

print("Polynomial Degree 4")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)

Polynomial Degree 4
Training Accuracy:  0
Testing  Accuracy:  0


### Inference

*Write your inference here*

...

## Problem 3: Overfitting and Underfitting (2 Marks)

**Let us say we have a dataset with little noise. Then a model is underfitting when:**

a) both the train and test errors are high

b) train error is low but test error is high

c) train error is high but the test error is low

d) both train and test errors are low


**If we choose the parameters of a model to get the best overfitting/underfitting tradeoff, we will always get a zero test error.**

a) True

b) False


**State which of the below statements is false with respect to underfitting vs overfitting.**

a) If the training set performance is roughly equal, underfitting is generally better.

b) An underfit model is simpler and can usually be improved by looking at where it fits badly.

c) An overfit model is often easier to change because it is easy to know where to start simplifying.

d) Neither overfitting nor underfitting is desirable.


In [ ]:
## Write your answers below




## Problem 4: Regularization (2 Marks)

Solve the problem using regularization (Lasso, Ridge and Elastic net) on the 3 polynomial functions defined in **Problem 2**.

Print out the train and test accuracy. Write your inference on the results

**Data**: X1_train, X1_test, Y1_train, Y1_test


### Polynomial Degree 2

#### Lasso Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Lasso regularizer
## to the 2nd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 2 : Lasso Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 2 : Lasso Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Ridge Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Ridge regularizer
## to the 2nd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 2 : Ridge Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 2 : Ridge Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Elastic net Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Elastic net regularizer
## to the 2nd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 2 : Elastic net Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 2 : Elastic net Regularization
Training Accuracy:  0
Testing  Accuracy:  0


### Polynomial Degree 3

#### Lasso Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Lasso regularizer
## to the 3rd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 3 : Lasso Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 3 : Lasso Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Ridge Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Ridge regularizer
## to the 3rd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 3 : Ridge Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 3 : Ridge Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Elastic net Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Elastic net regularizer
## to the 3rd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 3 : Elastic net Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 3 : Elastic net Regularization
Training Accuracy:  0
Testing  Accuracy:  0


### Polynomial Degree 4

#### Lasso Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Lasso regularizer
## to the 4th order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 4 : Lasso Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 4 : Lasso Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Ridge Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Ridge regularizer
## to the 4th order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 4 : Ridge Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 4 : Ridge Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Elastic net Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Elastic net regularizer
## to the 4th order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 4 : Elastic net Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 4 : Elastic net Regularization
Training Accuracy:  0
Testing  Accuracy:  0


### Inference

*Write your inference here*

...

## Problem 5: Logistic Regression (2 Marks)

Train a logistic regression model.
Print the F1 score, accuracy and confusion matrix for both training and testing.

**Data**: X2_train, X2_test, Y2_train, Y2_test

In [ ]:
### Write your code here



## Compute f1 score, accuracy and confusion matrix for both training and testing



## Print the above computed metrics
accuracy_train = 0
f1_train = 0
cf_train = [] # confusion matrix
accuracy_test = 0
f1_test = 0
cf_test = [] # confusion matrix


print("Logistic Regression")
print("Training Accuracy: ", accuracy_train)
print("Training F1 score: ", f1_train)
print("Training confusion matrix: ")
print(cf_train)

print("Testing  Accuracy: ", accuracy_test)
print("Testing  F1 score: ", f1_test)
print("Testing  confusion matrix: ")
print(cf_test)