<a href="https://colab.research.google.com/github/ntp3105/IISc-CCE-ML-AI-MLOps/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical AI and MLOps : Assignment 1

## Import libraries and fetch data

In [147]:
## DO NOT EDIT
import numpy as np
import pickle

!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-4LzDDmpH-v9mIgwDqa6cSF5XrVm-SXg' -O linear_regression.pkl
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-AtCVwrcpgFCvAD3gwkUz812DIxqK338' -O logistic_regression.pkl

X1_train, X1_test, Y1_train, Y1_test, X2_train, X2_test, Y2_train, Y2_test = [[] for _ in range(8)]

with open("/content/linear_regression.pkl", 'rb') as f:
    X1_train, X1_test, Y1_train, Y1_test = pickle.load(f)

with open("/content/logistic_regression.pkl", 'rb') as f:
    X2_train, X2_test, Y2_train, Y2_test = pickle.load(f)

--2023-09-02 10:11:28--  https://docs.google.com/uc?export=download&id=1-4LzDDmpH-v9mIgwDqa6cSF5XrVm-SXg
Resolving docs.google.com (docs.google.com)... 142.251.2.139, 142.251.2.101, 142.251.2.102, ...
Connecting to docs.google.com (docs.google.com)|142.251.2.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-10-0s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ffc47pnvhoujqiev5g97n7t11vn9q6dd/1693649475000/06549736550030827657/*/1-4LzDDmpH-v9mIgwDqa6cSF5XrVm-SXg?e=download&uuid=7b6c899f-7827-45ec-8c99-088e530f35da [following]
--2023-09-02 10:11:28--  https://doc-10-0s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ffc47pnvhoujqiev5g97n7t11vn9q6dd/1693649475000/06549736550030827657/*/1-4LzDDmpH-v9mIgwDqa6cSF5XrVm-SXg?e=download&uuid=7b6c899f-7827-45ec-8c99-088e530f35da
Resolving doc-10-0s-docs.googleusercontent.com (doc-10-0s-docs.googleusercontent.com)... 142.251.2.132, 2607:f8b0:4023:

In [148]:
X1_train = np.resize(X1_train, (len(X1_train), 1))
X1_test =  np.resize(X1_test,  (len(X1_test), 1))
Y1_train = np.resize(Y1_train, (len(Y1_train), 1))
Y1_test =  np.resize(Y1_test,  (len(Y1_test), 1))
print(X1_train.shape)
print(X1_test.shape)
print(Y1_train.shape)
print(Y1_test.shape)

(70, 1)
(30, 1)
(70, 1)
(30, 1)


In [149]:
Y2_train = np.resize(Y2_train, (len(Y2_train), 1))
Y2_test =  np.resize(Y2_test,  (len(Y2_test), 1))
print(X2_train.shape)
print(X2_test.shape)
print(Y2_train.shape)
print(Y2_test.shape)

(70, 20)
(30, 20)
(70, 1)
(30, 1)


In [150]:
print((X1_train**-1).shape)
print((X1_train).shape)
print(X1_test[0:5])
print(Y1_train.shape)
print(Y1_test[0:5])

(70, 1)
(70, 1)
[[ 6.26850875]
 [-5.75615029]
 [-5.98513959]
 [-9.76278328]
 [-6.04948187]]
(70, 1)
[[ 291.87875938]
 [-163.34294373]
 [-184.56229109]
 [-844.96063406]
 [-190.84148613]]


In [151]:
print(X2_train[0])
print(X2_test[0])
print(Y2_train[0:5])
print(Y2_test[0:5])

[-0.67857138  2.7670727   2.03131422  0.3322455  -1.2361682  -0.48420497
 -1.6533102   0.17205938 -1.14020401 -1.02420001 -1.41826043  0.26769137
  0.39235085  0.49597238 -2.04503375  0.75743566  2.50947819  0.53326592
  0.92774064 -1.3631717 ]
[ 1.59980278  0.34209474  1.39349879 -1.44936033 -0.94399061  0.00816769
 -0.87028399 -1.49635521  0.66575811  1.06385996 -1.73467213  0.05441906
 -0.05293944  0.82191122  0.04120958 -1.71024922  0.49349984  0.124863
 -0.22401342  0.47682353]
[[0]
 [1]
 [1]
 [0]
 [0]]
[[0]
 [0]
 [0]
 [0]
 [1]]


## Problem 1: Linear Regression (2 Marks)

Train a linear regression model for the above set of data. Use MSE(Mean Squared Error) as the loss function.

Print out the train accuracy and test accuracy.

**Data**: X1_train, X1_test, Y1_train, Y1_test

In [ ]:
### Write your code here
## Solve the question using normal equation
# Normal equation is Y1_train = regression coefficients or theta * X1_train
# theta = Y1_train * inv(X1_train)
theta = np.dot(Y1_train.T,(X1_train)**-1)
print("theta:", theta)

## Define the hypothesis function for linear regression
#Answer: Hypothesis y_hat =  beta_1*X1_train
#Cost_function = (np.sum(Y1_train - (bias + weight_1*X1_train) ))/len(Y1_train)
#print(Y1_train[0:5])

## Use linear regression to train the model

Regression_coefficient = (np.dot(X1_train.T,X1_train)**-1)*np.dot(X1_train.T,Y1_train)
print("Regression_coefficient: ", Regression_coefficient)
Y1_Lin_NoBias = Regression_coefficient*X1_train
print(Y1_Lin_NoBias.shape)
## Compute the training and testing loss using MSE error
Post_training_error = np.sum((Y1_train - Regression_coefficient*X1_train)**2)/len(Y1_train)
#print("Post Training Error: ", Post_training_error)

test_error = np.sum((Y1_test - Regression_coefficient*X1_test)**2)/len(Y1_test)
## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = Post_training_error
loss_test = test_error

print("Linear Regression")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)

theta: [[2781.59003867]]
Regression_coefficient:  [[66.1311054]]
(70, 1)
Linear Regression
Training Loss:  27415.39655697824
Testing  Loss:  44432.264978342


In [ ]:
ones_column = np.ones((X1_train.shape[0], 1))
X1_train_mod = np.hstack((ones_column, X1_train))

ones_column = np.ones((X1_test.shape[0], 1))
X1_test_mod = np.hstack((ones_column, X1_test))

Y1_train_mod = np.resize(Y1_train, (len(Y1_train), 1))
Y1_test_mod =  np.resize(Y1_test,  (len(Y1_test), 1))

In [ ]:
#This code snippet is to implement simple linear regression by implementing bias along with regression coefficient.
#X1_train and X1_test has been modified to add 2nd column as ones, because x value is 1 for bias values.

Regression_coefficients = np.dot(np.linalg.pinv(np.dot(X1_train_mod.T, X1_train_mod)), np.dot(X1_train_mod.T, Y1_train_mod))
print("Regression_coefficient: ", Regression_coefficients)
Y1_Lin_Bias = np.dot(X1_train_mod, Regression_coefficients)
print(Y1_Lin_Bias.shape)

## Compute the training and testing loss using MSE error
Post_training_error = np.sum((Y1_train_mod - np.dot(X1_train_mod, Regression_coefficients))**2)/len(Y1_train_mod)
print("Post Training Error: ", Post_training_error)
test_error = np.sum((Y1_test_mod - np.dot(X1_test_mod, Regression_coefficients))**2)/len(Y1_test_mod)

## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = Post_training_error
loss_test = test_error
print("Linear Regression")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)


Regression_coefficient:  [[47.21637965]
 [65.15344921]]
(70, 1)
Post Training Error:  25222.28423671403
Linear Regression
Training Loss:  25222.28423671403
Testing  Loss:  41716.624929654376


## Problem 2: Polynomial Regression (2 Marks)

Solve the above problem using atleast 3 different hypothesis functions with polynomial degree 2, 3 and 4.

Print out the train accuracy and test accuracy. Write your inference on the results.

**Data**: X1_train, X1_test, Y1_train, Y1_test

In [152]:
ones_column = np.ones((X1_train.shape[0], 1))
X1_train_poly2 = np.hstack((ones_column, X1_train, X1_train**2))
print(X1_train_poly2[0:5])

ones_column = np.ones((X1_test.shape[0], 1))
X1_test_poly2 = np.hstack((ones_column, X1_test, X1_test**2))
print(X1_test_poly2[0:3])

Y1_train_poly2 = np.resize(Y1_train, (len(Y1_train), 1))
Y1_test_poly2 =  np.resize(Y1_test,  (len(Y1_test), 1))
print(X1_train_poly2.shape)
print(X1_test_poly2.shape)
print(Y1_train_poly2.shape)
print(Y1_test_poly2.shape)

[[ 1.         -8.85376401 78.38913723]
 [ 1.         -2.5895495   6.70576661]
 [ 1.          8.08186325 65.31651353]
 [ 1.         -4.97550386 24.75563861]
 [ 1.          5.49334111 30.17679656]]
[[ 1.          6.26850875 39.29420194]
 [ 1.         -5.75615029 33.13326616]
 [ 1.         -5.98513959 35.82189591]]
(70, 3)
(30, 3)
(70, 1)
(30, 1)


### Polynomial Degree 2

In [ ]:
### Write your code here
## Define the hypothesis function
#Hypothesis = [Beta_0 * X1_train[0] + Beta_1 * X1_train[1] + Beta_2 * X1_train[2]]
#Regression_cofficients = Beta = [Beta_0, Beta_1, Beta_2]
#Hypothesis = [Beta] * X1_train


## Use polynomial regression to train the model
#Using Normal equation, Regression_cofficients = inv(X1_train.T*X1_train)*X1_train.T*Y1_train
Regression_coefficients_poly2 = np.dot(np.linalg.pinv(np.dot(X1_train_poly2.T, X1_train_poly2)), np.dot(X1_train_poly2.T, Y1_train_poly2))
print("Regression_coefficient: ", Regression_coefficients_poly2)
Y1_Poly2 = np.dot(X1_train_poly2, Regression_coefficients_poly2)
print(Y1_Poly2.shape)

## Compute the training and testing loss
Training_error = np.sum((Y1_train_poly2 - np.dot(X1_train_poly2, Regression_coefficients_poly2))**2)/len(Y1_train_poly2)
test_error = np.sum((Y1_test_poly2 - np.dot(X1_test_poly2, Regression_coefficients_poly2))**2)/len(Y1_test_poly2)


## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = Training_error
loss_test = test_error

print("Polynomial Degree 2")
print("Training loss: ", loss_train)
print("Testing  loss: ", loss_test)

Regression_coefficient:  [[-5.81412195]
 [64.01720536]
 [ 1.42086134]]
(70, 1)
Polynomial Degree 2
Training loss:  23308.50305148525
Testing  loss:  36380.348114078115


In [ ]:
ones_column = np.ones((X1_train.shape[0], 1))
X1_train_poly3 = np.hstack((ones_column, X1_train, X1_train**2, X1_train**3))
print(X1_train_poly3[0:5])

ones_column = np.ones((X1_test.shape[0], 1))
X1_test_poly3 = np.hstack((ones_column, X1_test, X1_test**2, X1_test**3))
print(X1_test_poly3[0:3])

Y1_train_poly3 = np.resize(Y1_train, (len(Y1_train), 1))
Y1_test_poly3 =  np.resize(Y1_test,  (len(Y1_test), 1))
print(X1_train_poly3.shape)
print(X1_test_poly3.shape)
print(Y1_train_poly3.shape)
print(Y1_test_poly3.shape)

[[   1.           -8.85376401   78.38913723 -694.03892235]
 [   1.           -2.5895495     6.70576661  -17.36491455]
 [   1.            8.08186325   65.31651353  527.87913012]
 [   1.           -4.97550386   24.75563861 -123.17177536]
 [   1.            5.49334111   30.17679656  165.77143712]]
[[   1.            6.26850875   39.29420194  246.31604869]
 [   1.           -5.75615029   33.13326616 -190.72005959]
 [   1.           -5.98513959   35.82189591 -214.39904741]]
(70, 4)
(30, 4)
(70, 1)
(30, 1)


### Polynomial Degree 3

In [ ]:
### Write your code here
## Define the hypothesis function
#Hypothesis = [Beta_0 * X1_train[0] + Beta_1 * X1_train[1] + Beta_2 * X1_train[2] + Beta_3 * X1_train[3]]
#Regression_cofficients = Beta = [Beta_0, Beta_1, Beta_2, Beta_3]
#Hypothesis = [Beta] * X1_train


## Use polynomial regression to train the model
#Using Normal equation, Regression_cofficients = inv(X1_train.T*X1_train)*X1_train.T*Y1_train
Regression_coefficients_poly3 = np.dot(np.linalg.pinv(np.dot(X1_train_poly3.T, X1_train_poly3)), np.dot(X1_train_poly3.T, Y1_train_poly3))
print("Regression_coefficient: ", Regression_coefficients_poly3)

Y1_Poly3 = np.dot(X1_train_poly3, Regression_coefficients_poly3)
print(Y1_Poly3.shape)

## Compute the training and testing loss
Training_error = np.sum((Y1_train_poly3 - np.dot(X1_train_poly3, Regression_coefficients_poly3))**2)/len(Y1_train_poly3)
test_error = np.sum((Y1_test_poly3 - np.dot(X1_test_poly3, Regression_coefficients_poly3))**2)/len(Y1_test_poly3)


## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = Training_error
loss_test = test_error

print("Polynomial Degree 3")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)

Regression_coefficient:  [[-4.29736247e-11]
 [ 1.00000000e+00]
 [ 1.00000000e+00]
 [ 1.00000000e+00]]
(70, 1)
Polynomial Degree 3
Training Loss:  7.92854562673667e-22
Testing  Loss:  8.283010751786646e-22


### Polynomial Degree 4

In [ ]:
ones_column = np.ones((X1_train.shape[0], 1))
X1_train_poly4 = np.hstack((ones_column, X1_train, X1_train**2, X1_train**3, X1_train**4))
print(X1_train_poly4[0:5])

ones_column = np.ones((X1_test.shape[0], 1))
X1_test_poly4 = np.hstack((ones_column, X1_test, X1_test**2, X1_test**3, X1_test**4))
print(X1_test_poly4[0:3])

Y1_train_poly4 = np.resize(Y1_train, (len(Y1_train), 1))
Y1_test_poly4 =  np.resize(Y1_test,  (len(Y1_test), 1))
print(X1_train_poly4.shape)
print(X1_test_poly4.shape)
print(Y1_train_poly4.shape)
print(Y1_test_poly4.shape)

[[ 1.00000000e+00 -8.85376401e+00  7.83891372e+01 -6.94038922e+02
   6.14485684e+03]
 [ 1.00000000e+00 -2.58954950e+00  6.70576661e+00 -1.73649146e+01
   4.49673058e+01]
 [ 1.00000000e+00  8.08186325e+00  6.53165135e+01  5.27879130e+02
   4.26624694e+03]
 [ 1.00000000e+00 -4.97550386e+00  2.47556386e+01 -1.23171775e+02
   6.12841643e+02]
 [ 1.00000000e+00  5.49334111e+00  3.01767966e+01  1.65771437e+02
   9.10639051e+02]]
[[ 1.00000000e+00  6.26850875e+00  3.92942019e+01  2.46316049e+02
   1.54403431e+03]
 [ 1.00000000e+00 -5.75615029e+00  3.31332662e+01 -1.90720060e+02
   1.09781333e+03]
 [ 1.00000000e+00 -5.98513959e+00  3.58218959e+01 -2.14399047e+02
   1.28320823e+03]]
(70, 5)
(30, 5)
(70, 1)
(30, 1)


In [ ]:
### Write your code here
## Define the hypothesis function
#Hypothesis = [Beta_0 * X1_train[0] + Beta_1 * X1_train[1] + Beta_2 * X1_train[2] + Beta_3 * X1_train[3]]
#Regression_cofficients = Beta = [Beta_0, Beta_1, Beta_2, Beta_3]
#Hypothesis = [Beta] * X1_train


## Use polynomial regression to train the model
#Using Normal equation, Regression_cofficients = inv(X1_train.T*X1_train)*X1_train.T*Y1_train
Regression_coefficients_poly4 = np.dot(np.linalg.pinv(np.dot(X1_train_poly4.T, X1_train_poly4)), np.dot(X1_train_poly4.T, Y1_train_poly4))
print("Regression_coefficient: ", Regression_coefficients_poly4)
Y1_Poly4 = np.dot(X1_train_poly4, Regression_coefficients_poly4)
print(Y1_Poly4.shape)

## Compute the training and testing loss
Training_error = np.sum((Y1_train_poly4 - np.dot(X1_train_poly4, Regression_coefficients_poly4))**2)/len(Y1_train_poly4)
test_error = np.sum((Y1_test_poly4 - np.dot(X1_test_poly4, Regression_coefficients_poly4))**2)/len(Y1_test_poly4)


## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = Training_error
loss_test = test_error

print("Polynomial Degree 4")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)

Regression_coefficient:  [[1.04554861e-10]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [4.63908321e-14]]
(70, 1)
Polynomial Degree 4
Training Loss:  2.786446139990528e-21
Testing  Loss:  2.7485570890912254e-21


In [ ]:
# Calculate the coefficients (Theta) using the normal equation
X_transpose_X = np.dot(X1_train_poly4.T, X1_train_poly4)
X_transpose_y = np.dot(X1_train_poly4.T, Y1_train_poly4)
coefficients = np.linalg.solve(X_transpose_X, X_transpose_y)

# The coefficients represent the coefficients of the polynomial terms in increasing order of degree
print("Coefficients for Polynomial Regression:")
for i, coeff in enumerate(coefficients):
    print(f"Theta_{i}:", coeff)

## Compute the training and testing loss
Training_error = np.sum((Y1_train_poly4 - np.dot(X1_train_poly4, Regression_coefficients_poly4))**2)/len(Y1_train_poly4)
test_error = np.sum((Y1_test_poly4 - np.dot(X1_test_poly4, Regression_coefficients_poly4))**2)/len(Y1_test_poly4)


## Print the training and testing loss
## update the below two variables to print the model's loss
loss_train = Training_error
loss_test = test_error

print("Polynomial Degree 4")
print("Training Loss: ", loss_train)
print("Testing  Loss: ", loss_test)

Coefficients for Polynomial Regression:
Theta_0: [-1.14347785e-12]
Theta_1: [1.]
Theta_2: [1.]
Theta_3: [1.]
Theta_4: [-9.58115424e-16]
Polynomial Degree 4
Training Loss:  2.786446139990528e-21
Testing  Loss:  2.7485570890912254e-21


In [ ]:
#import matplotlib.pyplot as plt
#plt.plot(X1_train, Y1_train)#, label='training set',                           color='magenta')
#plt.plot(X1_train, Y1_Lin_NoBias, label='y=b1*x',                            color='blue')
#plt.plot(X1_train, Y1_Lin_Bias, label='y=b0 + b1*x',                         color='red')
#plt.plot(X1_train, Y1_Poly2, label='y=b0 + b1*x + b2*x^2',                   color='orange')
#plt.plot(X1_train, Y1_Poly3, label='y=b0 + b1*x + b2*x^2 + b3*x^3',          color='green')
#plt.plot(X1_train, Y1_Poly4, label='y=b0 + b1*x + b2*x^2 + b3*x^3 + b4*x^4', color='black')

### Inference

The training error and testing error changes with degree of polynomial. Between Simple linear regression, the hypothesis function without bias and with bias, the latter showed higher accuracy in terms of lower MSE than without bias. This confirms the observation that simple linear regression with bias is always better than the one without bias.
Comparing Polynomial regression with degree 2,3 and 4, the training error and test error for degree 3 is the lowest, followed by degree 4 and then degree 2.
Training and test error are both ~e-21. So the model isnt overfitting or underfitting.



## Problem 3: Overfitting and Underfitting (2 Marks)

**Let us say we have a dataset with little noise. Then a model is underfitting when:**

a) both the train and test errors are high

b) train error is low but test error is high

c) train error is high but the test error is low

d) both train and test errors are low


**If we choose the parameters of a model to get the best overfitting/underfitting tradeoff, we will always get a zero test error.**

a) True

b) False


**State which of the below statements is false with respect to underfitting vs overfitting.**

a) If the training set performance is roughly equal, underfitting is generally better.

b) An underfit model is simpler and can usually be improved by looking at where it fits badly.

c) An overfit model is often easier to change because it is easy to know where to start simplifying.

d) Neither overfitting nor underfitting is desirable.


## Write your answers below
For the dataset with little noise, it underfits **a) when both the train and test errors are high**

If we choose the parameters of a model to get the best overfitting/underfitting tradeoff, we will always get a zero test error. **FALSE**

State which of the below statements is false with respect to underfitting vs overfitting:

**d) Neither overfitting nor underfitting is desirable.**

## Problem 4: Regularization (2 Marks)

Solve the problem using regularization (Lasso, Ridge and Elastic net) on the 3 polynomial functions defined in **Problem 2**.

Print out the train and test accuracy. Write your inference on the results

**Data**: X1_train, X1_test, Y1_train, Y1_test


### Polynomial Degree 2

#### Lasso Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Lasso regularizer
## to the 2nd order hypothesis function that you defined earlier

#Regression_cofficients = Beta = [Beta_0, Beta_1, Beta_2]
#Hypothesis = [Beta_0 * X1_train[0] + Beta_1 * X1_train[1] + Beta_2 * X1_train[2]]
#Hypothesis = [Beta] * X1_train

## Use polynomial regression to train the model

# Define (hyper)parameters for Gradient descent algorithm
alpha = 0.001  # Learning rate
lambda_ = 0.5  # Regularization parameter (lambda is L2 penalty)
num_iterations = 1000 #Nr of iteration for GD to run
m, n = X1_train_poly2.shape # no_of_training_examples, no_of_features

#print(X1_test_poly2.T.shape)
# Initialize coefficients
Beta = np.zeros(n)  #  3 coefficients [Beta_0, Beta_1, Beta_2]
Beta = np.resize(Beta, (len(Beta), 1))
#print(Beta.shape)

# Gradient Descent
for _ in range(num_iterations):
# Calculate predictions
    predictions = np.dot(X1_test_poly2, Regression_coefficients_poly2)


# Compute errors
    errors = predictions - Y1_test_poly2
    #print(errors.shape)
# Compute gradient with regularization (except for theta_0)
    gradient = (2/m) * np.dot(X1_test_poly2.T, errors) + (2*lambda_/m) * Beta
#   print(gradient.shape)
    gradient[0] = (2/m) *np.sum(errors)  # Exclude regularization for theta_0
    #print(gradient)
# Update coefficients meaning bias and weights
    Beta -= alpha*gradient
# Print coefficients
print("Ridge Coefficients:", Beta)

## Compute the training and testing accuracy
Training_error = np.sum((Y1_train_poly2 - np.dot(X1_train_poly2, Regression_coefficients_poly2))**2)/len(Y1_train_poly2)
Test_error = np.sum((Y1_test_poly2 - np.dot(X1_test_poly2, Regression_coefficients_poly2))**2)/len(Y1_test_poly2)

## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = Training_error
accuracy_test = Test_error

print("Polynomial Degree 2 : Lasso Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

#### Ridge Regularization

In [187]:
### Write your code here
## Define a new hypothesis function by adding a Lasso regularizer
## to the 2nd order hypothesis function that you defined earlier

#Regression_cofficients = Beta = [Beta_0, Beta_1, Beta_2]
#Hypothesis = [Beta_0 * X1_train[0] + Beta_1 * X1_train[1] + Beta_2 * X1_train[2]]
#Hypothesis = [Beta] * X1_train

## Use polynomial regression to train the model

# Define (hyper)parameters for Gradient descent algorithm
alpha = 0.001  # Learning rate
lambda_ = 0.5  # Regularization parameter (lambda is L2 penalty)
num_iterations = 1000 #Nr of iteration for GD to run
m, n = X1_train_poly2.shape # no_of_training_examples, no_of_features

#print(X1_test_poly2.T.shape)
# Initialize coefficients
Beta = np.zeros(n)  #  3 coefficients [Beta_0, Beta_1, Beta_2]
Beta = np.resize(Beta, (len(Beta), 1))
#print(Beta.shape)

# Gradient Descent
for _ in range(num_iterations):
# Calculate predictions
    predictions = np.dot(X1_test_poly2, Regression_coefficients_poly2)


# Compute errors
    errors = predictions - Y1_test_poly2
    #print(errors.shape)
# Compute gradient with regularization (except for theta_0)
    gradient = (2/m) * np.dot(X1_test_poly2.T, errors) + (2*lambda_/m) * Beta
#   print(gradient.shape)
    gradient[0] = (2/m) *np.sum(errors)  # Exclude regularization for theta_0
    #print(gradient)
# Update coefficients meaning bias and weights
    Beta -= alpha*gradient
# Print coefficients
print("Ridge Coefficients:", Beta)

## Compute the training and testing accuracy
Training_error = np.sum((Y1_train_poly2 - np.dot(X1_train_poly2, Regression_coefficients_poly2))**2)/len(Y1_train_poly2)
Test_error = np.sum((Y1_test_poly2 - np.dot(X1_test_poly2, Regression_coefficients_poly2))**2)/len(Y1_test_poly2)

## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = Training_error
accuracy_test = Test_error

print("Polynomial Degree 2 : Ridge Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

(3, 30)
(3, 1)
Ridge Coefficients: [[   3.93754685]
 [ 219.56884414]
 [1232.10923963]]
Polynomial Degree 2 : Ridge Regularization
Training Accuracy:  23308.50305148525
Testing  Accuracy:  36380.348114078115


#### Elastic net Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Elastic net regularizer
## to the 2nd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 2 : Elastic net Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 2 : Elastic net Regularization
Training Accuracy:  0
Testing  Accuracy:  0


### Polynomial Degree 3

#### Lasso Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Lasso regularizer
## to the 3rd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 3 : Lasso Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 3 : Lasso Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Ridge Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Ridge regularizer
## to the 3rd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 3 : Ridge Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 3 : Ridge Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Elastic net Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Elastic net regularizer
## to the 3rd order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 3 : Elastic net Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 3 : Elastic net Regularization
Training Accuracy:  0
Testing  Accuracy:  0


### Polynomial Degree 4

#### Lasso Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Lasso regularizer
## to the 4th order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 4 : Lasso Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 4 : Lasso Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Ridge Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Ridge regularizer
## to the 4th order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 4 : Ridge Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 4 : Ridge Regularization
Training Accuracy:  0
Testing  Accuracy:  0


#### Elastic net Regularization

In [ ]:
### Write your code here
## Define a new hypothesis function by adding a Elastic net regularizer
## to the 4th order hypothesis function that you defined earlier



## Use polynomial regression to train the model



## Compute the training and testing accuracy



## Print the training and testing accuracy
## update the below two variables to print the model's accuracy
accuracy_train = 0
accuracy_test = 0

print("Polynomial Degree 4 : Elastic net Regularization")
print("Training Accuracy: ", accuracy_train)
print("Testing  Accuracy: ", accuracy_test)

Polynomial Degree 4 : Elastic net Regularization
Training Accuracy:  0
Testing  Accuracy:  0


### Inference

*Write your inference here*

...

## Problem 5: Logistic Regression (2 Marks)

Train a logistic regression model.
Print the F1 score, accuracy and confusion matrix for both training and testing.

**Data**: X2_train, X2_test, Y2_train, Y2_test

In [ ]:
### Write your code here



## Compute f1 score, accuracy and confusion matrix for both training and testing



## Print the above computed metrics
accuracy_train = 0
f1_train = 0
cf_train = [] # confusion matrix
accuracy_test = 0
f1_test = 0
cf_test = [] # confusion matrix


print("Logistic Regression")
print("Training Accuracy: ", accuracy_train)
print("Training F1 score: ", f1_train)
print("Training confusion matrix: ")
print(cf_train)

print("Testing  Accuracy: ", accuracy_test)
print("Testing  F1 score: ", f1_test)
print("Testing  confusion matrix: ")
print(cf_test)

Logistic Regression
Training Accuracy:  0
Training F1 score:  0
Training confusion matrix: 
[]
Testing  Accuracy:  0
Testing  F1 score:  0
Testing  confusion matrix: 
[]
