# Practical AI and MLOps : Assignment 3


### Download the dataset.

Download the dataset attached with the assignment and store it in a pandas dataframe `df`. You are free to change the names as you like. You can split the datasets using `train_test_split` function from the `scikit-learn` library.

**1st dataset:** (df) For problem 1

In [1]:
import pandas as pd
df = pd.read_csv('Iris.csv')
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

## Problem 1 (5 marks)

# MLP model for iris dataset


You have to design and implement neural network models for multi-class classification using both a Multi-Layer Perceptron (MLP) and a Convolutional Neural Network (CNN). The dataset you will be working with contains samples from multiple classes. You need to experiment with different activation functions and loss functions for both models to find the best combinations for this task.

Instructions:

1. Load the multi-class dataset.

2. Preprocess the dataset as needed, including data splitting and normalization.

3. **Implement an MLP model**

Implement an MLP model with the following specifications:

*   Input layer with an appropriate number of neurons based on the dataset's features.
*   At least one hidden layer with a flexible number of neurons (you can experiment with this).
*   An output layer with neurons corresponding to the number of classes in the dataset.

Train the MLP model using the following settings:
*   Use two different activation functions for the hidden layers (e.g., ReLU and Sigmoid).
*   Use at least two different loss functions (e.g., Cross-Entropy and Mean Squared Error).
*   Experiment with various hyperparameters like learning rate, batch size, and the number of hidden neurons.

For each combination of activation function and loss function, train the model and evaluate its performance on the test set using appropriate metrics (e.g., accuracy, F1-score).

Report the following for each combination:
*   Accuracy on the validation set.
*   F1-score on the validation set.
*   Confusion Matrix.

4. **Implement a CNN model**

Implement a 2D CNN model with the following specifications:

*   Convolutional layers with appropriate filters and kernel sizes.
*   At least one fully connected (dense) layer.
*   An output layer with neurons corresponding to the number of classes in the dataset.

Train the CNN model using the following settings:
*   Use two different activation functions for the convolutional and dense layers (e.g., ReLU and Tanh).
*   Use at least two different loss functions (e.g., Cross-Entropy and Categorical Hinge Loss).
*   Experiment with various hyperparameters like learning rate, batch size, and the number of filters.

For each combination of activation function and loss function, train the model and evaluate its performance on the test set using appropriate metrics (e.g., accuracy, F1-score).

Report the following for each combination:
*   Accuracy on the validation set.
*   F1-score on the validation set.
*   Confusion Matrix.

In [42]:
# Import libraries 
import numpy as np

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

from tensorflow import keras
from tensorflow.keras import layers

In [35]:
# Load the multi-class dataset.
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [36]:
print(f"Shape of feature matrix, X is {X.shape} and target vector, y is {y.shape}")
input_shape = X.shape[1]
input_shape

Shape of feature matrix, X is (150, 4) and target vector, y is (150,)


4

In [37]:
# Preprocess the dataset as needed, including data splitting and normalization.
# Split the data into training and testing sets, no need of validation tests
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
'''
Implement an MLP model with the following specifications:

    1) Input layer with an appropriate number of neurons based on the dataset's features.
    2) At least one hidden layer with a flexible number of neurons (you can experiment with this).
    3) An output layer with neurons corresponding to the number of classes in the dataset.
'''
def MLP_model(num_hidden_layers, num_neurons_per_layer, input_shape, activation_func):
    model = keras.Sequential()
    model.add(keras.layers.Input(shape=input_shape))
    
    for _ in range(num_hidden_layers):
        model.add(keras.layers.Dense(num_neurons_per_layer, activation=activation_func))
        
    model.add(keras.layers.Dense(3, activation = 'softmax')) # Output layer for classification
    return model                                    

In [45]:
# Define different activation functions and loss functions
activation_functions = ['relu', 'sigmoid']
loss_functions = ['categorical_crossentropy', 'mean_squared_error']
learning_rates = [0.001, 0.01]
batch_sizes = [16, 32]
hidden_neurons = [16, 32]
hidden_layers = [1,2,3,4,5]

# Iterate through the variations
for activation_func in activation_functions:
    for loss in loss_functions:
        for learning_rate in learning_rates:
            for batch_size in batch_sizes:
                for num_neurons_per_layer in hidden_neurons:
                    for num_hidden_layers in hidden_layers:
                        # Create the model with user-specified parameters
                        mlp_model = MLP_model(num_hidden_layers, num_neurons_per_layer, input_shape, activation_func)
                        
                        # Compile the model with user-specified learning rate
                        optimizer = keras.optimizers.Adam(learning_rate=learning_rate)
                        mlp_model.compile(loss=loss, optimizer=optimizer, metrics=['accuracy'])
                        
                        # Train the model
                        mlp_model.fit(X_train, keras.utils.to_categorical(y_train), epochs=50, batch_size=batch_size, verbose=0)
    
                        # Evaluate the model
                        accuracy = mlp_model.evaluate(X_test, keras.utils.to_categorical(y_test), verbose=0)
            
                        # Make predictions
                        y_pred = mlp_model.predict(X_test)
                        y_pred_classes = np.argmax(y_pred, axis=1)

                        # Print the results
                        print(f"Activation Function: {activation_func}, Loss Function: {loss}, Learning Rate: {learning_rate}, "
                          f"Batch Size: {batch_size}, Hidden Neurons: {num_neurons_per_layer}")
                        print("Accuracy: {:.2f}%".format(accuracy[1] * 100))
                        print("Classification Report:")
                        print(classification_report(y_test, y_pred_classes))
                        print("Confusion Matrix:")
                        print(confusion_matrix(y_test, y_pred_classes))
                        print()


2/2 [==============================] - 0s 0s/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 16
Accuracy: 84.44%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.46      0.63        13
           2       0.65      1.00      0.79        13

    accuracy                           0.84        45
   macro avg       0.88      0.82      0.81        45
weighted avg       0.90      0.84      0.83        45

Confusion Matrix:
[[19  0  0]
 [ 0  6  7]
 [ 0  0 13]]

2/2 [==============================] - 0s 10ms/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 16
Accuracy: 91.11%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.0

2/2 [==============================] - 0s 10ms/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 32
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 0s/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 16
Accuracy: 82.22%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.

2/2 [==============================] - 0s 10ms/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 16, Hidden Neurons: 16
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 20ms/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 16, Hidden Neurons: 16
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1

2/2 [==============================] - 0s 2ms/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 32, Hidden Neurons: 32
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 2ms/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 32, Hidden Neurons: 32
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.0

2/2 [==============================] - 0s 10ms/step
Activation Function: relu, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 32
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 10ms/step
Activation Function: relu, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 32
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1

2/2 [==============================] - 0s 20ms/step
Activation Function: relu, Loss Function: mean_squared_error, Learning Rate: 0.01, Batch Size: 16, Hidden Neurons: 16
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 2ms/step
Activation Function: relu, Loss Function: mean_squared_error, Learning Rate: 0.01, Batch Size: 16, Hidden Neurons: 16
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00

2/2 [==============================] - 0s 10ms/step
Activation Function: relu, Loss Function: mean_squared_error, Learning Rate: 0.01, Batch Size: 32, Hidden Neurons: 16
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 10ms/step
Activation Function: relu, Loss Function: mean_squared_error, Learning Rate: 0.01, Batch Size: 32, Hidden Neurons: 32
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.0

C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 22ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 32
Accuracy: 86.67%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.54      0.70        13
           2       0.68      1.00      0.81        13

    accuracy                           0.87        45
   macro avg       0.89      0.85      0.84        45
weighted avg       0.91      0.87      0.86        45

Confusion Matrix:
[[19  0  0]
 [ 0  7  6]
 [ 0  0 13]]

2/2 [==============================] - 0s 12ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 32
Accuracy: 88.89%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1  

C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 20ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 16
Accuracy: 68.89%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.48      0.92      0.63        13
           2       0.00      0.00      0.00        13

    accuracy                           0.69        45
   macro avg       0.49      0.64      0.54        45
weighted avg       0.56      0.69      0.60        45

Confusion Matrix:
[[19  0  0]
 [ 0 12  1]
 [ 0 13  0]]

2/2 [==============================] - 0s 20ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 16
Accuracy: 28.89%
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1  

C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 10ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 16
Accuracy: 51.11%
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.37      1.00      0.54        13
           2       1.00      0.77      0.87        13

    accuracy                           0.51        45
   macro avg       0.46      0.59      0.47        45
weighted avg       0.40      0.51      0.41        45

Confusion Matrix:
[[ 0 19  0]
 [ 0 13  0]
 [ 0  3 10]]



C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 2ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 32
Accuracy: 84.44%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.46      0.63        13
           2       0.65      1.00      0.79        13

    accuracy                           0.84        45
   macro avg       0.88      0.82      0.81        45
weighted avg       0.90      0.84      0.83        45

Confusion Matrix:
[[19  0  0]
 [ 0  6  7]
 [ 0  0 13]]

2/2 [==============================] - 0s 10ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 32
Accuracy: 86.67%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1   

C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 20ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 16, Hidden Neurons: 32
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 8ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 16, Hidden Neurons: 32
Accuracy: 97.78%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1    

2/2 [==============================] - 0s 12ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 32, Hidden Neurons: 32
Accuracy: 97.78%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

Confusion Matrix:
[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]

2/2 [==============================] - 0s 40ms/step
Activation Function: sigmoid, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 32, Hidden Neurons: 32
Accuracy: 97.78%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1    

C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 8ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 16
Accuracy: 71.11%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.00      0.00      0.00        13
           2       0.50      1.00      0.67        13

    accuracy                           0.71        45
   macro avg       0.50      0.67      0.56        45
weighted avg       0.57      0.71      0.61        45

Confusion Matrix:
[[19  0  0]
 [ 0  0 13]
 [ 0  0 13]]



C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 10ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 32
Accuracy: 86.67%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.54      0.70        13
           2       0.68      1.00      0.81        13

    accuracy                           0.87        45
   macro avg       0.89      0.85      0.84        45
weighted avg       0.91      0.87      0.86        45

Confusion Matrix:
[[19  0  0]
 [ 0  7  6]
 [ 0  0 13]]

2/2 [==============================] - 0s 10ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 16, Hidden Neurons: 32
Accuracy: 91.11%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00   

C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 8ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 16
Accuracy: 73.33%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.08      0.14        13
           2       0.52      1.00      0.68        13

    accuracy                           0.73        45
   macro avg       0.84      0.69      0.61        45
weighted avg       0.86      0.73      0.66        45

Confusion Matrix:
[[19  0  0]
 [ 0  1 12]
 [ 0  0 13]]

2/2 [==============================] - 0s 0s/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 16
Accuracy: 28.89%
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.00      

C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 0s/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 16
Accuracy: 35.56%
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.31      1.00      0.47        13
           2       1.00      0.23      0.38        13

    accuracy                           0.36        45
   macro avg       0.44      0.41      0.28        45
weighted avg       0.38      0.36      0.24        45

Confusion Matrix:
[[ 0 19  0]
 [ 0 13  0]
 [ 0 10  3]]



C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 8ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 32
Accuracy: 84.44%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.46      0.63        13
           2       0.65      1.00      0.79        13

    accuracy                           0.84        45
   macro avg       0.88      0.82      0.81        45
weighted avg       0.90      0.84      0.83        45

Confusion Matrix:
[[19  0  0]
 [ 0  6  7]
 [ 0  0 13]]

2/2 [==============================] - 0s 10ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 32
Accuracy: 86.67%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00    

C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 30ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.001, Batch Size: 32, Hidden Neurons: 32
Accuracy: 71.11%
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        19
           1       0.00      0.00      0.00        13
           2       0.52      1.00      0.68        13

    accuracy                           0.71        45
   macro avg       0.49      0.67      0.55        45
weighted avg       0.55      0.71      0.61        45

Confusion Matrix:
[[19  0  0]
 [ 1  0 12]
 [ 0  0 13]]



C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PTB3KOR\.conda\envs\ml-zoomcamp\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 [==============================] - 0s 8ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.01, Batch Size: 16, Hidden Neurons: 16
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 0s/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.01, Batch Size: 16, Hidden Neurons: 16
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      

2/2 [==============================] - 0s 12ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.01, Batch Size: 32, Hidden Neurons: 16
Accuracy: 100.00%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

2/2 [==============================] - 0s 10ms/step
Activation Function: sigmoid, Loss Function: mean_squared_error, Learning Rate: 0.01, Batch Size: 32, Hidden Neurons: 16
Accuracy: 95.56%
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92    

# CNN model for MNIST dataset

In [49]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# Load the MNIST dataset from the .npz file
with np.load('mnist.npz') as data:
    x_train = data['x_train']  # Training images
    y_train = data['y_train']  # Training labels
    x_test = data['x_test']    # Test images
    y_test = data['y_test']    # Test labels

# Preprocess the dataset
x_train = x_train.reshape(-1, 28, 28, 1) / 255.0
x_test = x_test.reshape(-1, 28, 28, 1) / 255.0
y_train = to_categorical(y_train, num_classes=10)
y_test = to_categorical(y_test, num_classes=10)

# Define different activation functions, loss functions, and hyperparameters
activation_functions = ['relu', 'tanh']
loss_functions = ['categorical_crossentropy', 'categorical_hinge']
learning_rates = [0.001, 0.01]
batch_sizes = [32, 64]
num_filters = [32, 64]

# Iterate through the combinations
for activation in activation_functions:
    for loss in loss_functions:
        for learning_rate in learning_rates:
            for batch_size in batch_sizes:
                for num_filter in num_filters:
                    # Build the CNN model
                    model = keras.Sequential()
                    model.add(layers.Conv2D(num_filter, (3, 3), activation=activation, input_shape=(28, 28, 1)))
                    model.add(layers.MaxPooling2D((2, 2)))
                    model.add(layers.Flatten())
                    model.add(layers.Dense(128, activation=activation))
                    model.add(layers.Dense(10, activation='softmax'))

                    # Compile the model with user-specified learning rate
                    optimizer = keras.optimizers.Adam(learning_rate=learning_rate)
                    model.compile(loss=loss, optimizer=optimizer, metrics=['accuracy'])

                    # Train the model
                    model.fit(x_train, y_train, epochs=5, batch_size=batch_size, verbose=0)

                    # Evaluate the model on the test set
                    y_pred = model.predict(x_test)
                    y_pred_classes = np.argmax(y_pred, axis=1)

                    # Calculate and print results
                    accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred_classes)
                    f1 = f1_score(np.argmax(y_test, axis=1), y_pred_classes, average='weighted')
                    cm = confusion_matrix(np.argmax(y_test, axis=1), y_pred_classes)

                    print(f"Activation Function: {activation}, Loss Function: {loss}, Learning Rate: {learning_rate}, "
                          f"Batch Size: {batch_size}, Number of Filters: {num_filter}")
                    print(f"Accuracy: {accuracy:.2f}")
                    print(f"F1 Score: {f1:.2f}")
                    print("Confusion Matrix:")
                    print(cm)
                    print()


313/313 [==============================] - 22s 69ms/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 32, Number of Filters: 32
Accuracy: 0.99
F1 Score: 0.99
Confusion Matrix:
[[ 975    0    1    1    0    0    0    0    2    1]
 [   0 1132    1    1    0    0    1    0    0    0]
 [   1    7 1016    1    1    0    1    5    0    0]
 [   0    0    1 1003    0    4    0    0    2    0]
 [   0    0    0    0  971    0    5    0    0    6]
 [   1    0    1    7    0  877    5    0    1    0]
 [   3    3    0    0    1    3  945    0    3    0]
 [   0    1   12    3    0    0    0 1005    1    6]
 [   4    0    6    4    1    5    1    2  947    4]
 [   0    1    0    1    9    2    1    3    1  991]]

313/313 [==============================] - 20s 64ms/step
Activation Function: relu, Loss Function: categorical_crossentropy, Learning Rate: 0.001, Batch Size: 32, Number of Filters: 64
Accuracy: 0.99
F1 Score: 0.99
Confusion Matrix:
[[

313/313 [==============================] - 16s 50ms/step
Activation Function: relu, Loss Function: categorical_hinge, Learning Rate: 0.001, Batch Size: 64, Number of Filters: 64
Accuracy: 0.98
F1 Score: 0.98
Confusion Matrix:
[[ 978    0    0    0    0    1    1    0    0    0]
 [   1 1122    2    2    0    2    2    2    2    0]
 [   6    8 1007    0    1    0    0    8    2    0]
 [   0    0    3  978    0   21    0    3    3    2]
 [   1    0    2    0  975    0    0    1    1    2]
 [   2    0    0    0    0  886    4    0    0    0]
 [   4    2    0    0    2    4  946    0    0    0]
 [   3    0   10    3    0    0    0 1008    1    3]
 [   8    0    5    2    3    5    3    4  941    3]
 [   6    4    0    4    7    6    1    5    2  974]]

313/313 [==============================] - 14s 45ms/step
Activation Function: relu, Loss Function: categorical_hinge, Learning Rate: 0.01, Batch Size: 32, Number of Filters: 32
Accuracy: 0.92
F1 Score: 0.92
Confusion Matrix:
[[ 962    0    1 

313/313 [==============================] - 11s 34ms/step
Activation Function: tanh, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 64, Number of Filters: 32
Accuracy: 0.95
F1 Score: 0.95
Confusion Matrix:
[[ 954    0    3    2    2    3    5    2    9    0]
 [   0 1113    4    4    1    0    3    1    9    0]
 [   8    3  973   16    9    0    0   12    9    2]
 [   2    0    4  977    0   17    0    4    3    3]
 [   0    1    1    0  956    0    3    1    2   18]
 [   4    0    0   20    1  848    5    0   13    1]
 [  19    2    2    0   15   11  905    0    4    0]
 [   1    2   12   13    7    2    0  972    4   15]
 [   4    1   18   19    8    7    3   14  889   11]
 [   5    4    1   10   32    6    0   22    6  923]]

313/313 [==============================] - 13s 40ms/step
Activation Function: tanh, Loss Function: categorical_crossentropy, Learning Rate: 0.01, Batch Size: 64, Number of Filters: 64
Accuracy: 0.91
F1 Score: 0.91
Confusion Matrix:
[[ 9

## Problem 2 (5 marks)


1.  Write an essay to explain the MLOps Lifecycle, including the integration of DevOps, DataOps, and ModelOps. Save it in a file named "README.md" ("README.txt")
2.   Create a public github repository.
3.   Commit the file containing the essay (in "step 1") to the main branch.
4.   Create and checkout to a new branch.
5.   Edit the "README.md" file and make some changes.
6.   Commit the changes to the new branch and send a pull request to the main branch.

Share the github repository url in the assignment.

Make sure to not make any changes to the repository after the due date. Penalty will be same as the earlier and the last edited time will be considered for it.



```
# Write your answers here
```

github repository url: https://github.com/ntp3105/IISc-CCE-ML-AI-MLOps/tree/main